<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="3" total="13" passed="6" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-29T13:31:42 IST" name="Default suite" finished-at="2024-07-29T13:50:16 IST" duration-ms="1113399">
    <groups>
    </groups>
    <test started-at="2024-07-29T13:31:42 IST" name="Default test" finished-at="2024-07-29T13:50:16 IST" duration-ms="1113399">
      <class name="mtestcases.TC_CreditAndDebit">
        <test-method signature="VoidOfSale()[pri:0, instance:mtestcases.TC_CreditAndDebit@6404f418]" started-at="2024-07-29T13:31:42 IST" name="VoidOfSale" finished-at="2024-07-29T13:32:21 IST" duration-ms="38670" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VoidOfSale -->
        <test-method is-config="true" signature="saveXLFile()[pri:0, instance:mtestcases.TC_CreditAndDebit@6404f418]" started-at="2024-07-29T13:32:21 IST" name="saveXLFile" finished-at="2024-07-29T13:32:24 IST" duration-ms="3438" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- saveXLFile -->
        <test-method signature="VoidOfSale()[pri:0, instance:mtestcases.TC_CreditAndDebit@6404f418]" started-at="2024-07-29T13:32:24 IST" name="VoidOfSale" finished-at="2024-07-29T13:33:01 IST" duration-ms="36638" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VoidOfSale -->
        <test-method is-config="true" signature="saveXLFile()[pri:0, instance:mtestcases.TC_CreditAndDebit@6404f418]" started-at="2024-07-29T13:33:01 IST" name="saveXLFile" finished-at="2024-07-29T13:33:04 IST" duration-ms="3333" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- saveXLFile -->
        <test-method signature="VoidOfSale()[pri:0, instance:mtestcases.TC_CreditAndDebit@6404f418]" started-at="2024-07-29T13:33:04 IST" name="VoidOfSale" finished-at="2024-07-29T13:33:37 IST" duration-ms="32355" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VoidOfSale -->
        <test-method is-config="true" signature="saveXLFile()[pri:0, instance:mtestcases.TC_CreditAndDebit@6404f418]" started-at="2024-07-29T13:33:37 IST" name="saveXLFile" finished-at="2024-07-29T13:33:40 IST" duration-ms="3299" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- saveXLFile -->
        <test-method signature="VoidOfSale()[pri:0, instance:mtestcases.TC_CreditAndDebit@6404f418]" started-at="2024-07-29T13:33:40 IST" name="VoidOfSale" finished-at="2024-07-29T13:34:12 IST" duration-ms="32253" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VoidOfSale -->
        <test-method is-config="true" signature="saveXLFile()[pri:0, instance:mtestcases.TC_CreditAndDebit@6404f418]" started-at="2024-07-29T13:34:12 IST" name="saveXLFile" finished-at="2024-07-29T13:34:16 IST" duration-ms="3182" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- saveXLFile -->
        <test-method signature="VoidOfSale()[pri:0, instance:mtestcases.TC_CreditAndDebit@6404f418]" started-at="2024-07-29T13:34:16 IST" name="VoidOfSale" finished-at="2024-07-29T13:34:48 IST" duration-ms="32940" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VoidOfSale -->
        <test-method is-config="true" signature="saveXLFile()[pri:0, instance:mtestcases.TC_CreditAndDebit@6404f418]" started-at="2024-07-29T13:34:48 IST" name="saveXLFile" finished-at="2024-07-29T13:34:52 IST" duration-ms="3318" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- saveXLFile -->
        <test-method signature="VoidOfSale()[pri:0, instance:mtestcases.TC_CreditAndDebit@6404f418]" started-at="2024-07-29T13:34:52 IST" name="VoidOfSale" finished-at="2024-07-29T13:37:53 IST" duration-ms="181311" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VoidOfSale -->
        <test-method is-config="true" signature="saveXLFile()[pri:0, instance:mtestcases.TC_CreditAndDebit@6404f418]" started-at="2024-07-29T13:37:53 IST" name="saveXLFile" finished-at="2024-07-29T13:37:57 IST" duration-ms="3454" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- saveXLFile -->
        <test-method signature="VoidOfSale()[pri:0, instance:mtestcases.TC_CreditAndDebit@6404f418]" started-at="2024-07-29T13:37:57 IST" name="VoidOfSale" finished-at="2024-07-29T13:40:58 IST" duration-ms="181539" status="FAIL">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index 0 out of bounds for length 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
at java.base/java.util.Objects.checkIndex(Objects.java:361)
at java.base/java.util.ArrayList.get(ArrayList.java:427)
at mtestcases.TC_CreditAndDebit.VoidOfSale(TC_CreditAndDebit.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VoidOfSale -->
        <test-method is-config="true" signature="saveXLFile()[pri:0, instance:mtestcases.TC_CreditAndDebit@6404f418]" started-at="2024-07-29T13:40:58 IST" name="saveXLFile" finished-at="2024-07-29T13:41:01 IST" duration-ms="3186" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- saveXLFile -->
        <test-method signature="VoidOfSale()[pri:0, instance:mtestcases.TC_CreditAndDebit@6404f418]" started-at="2024-07-29T13:41:01 IST" name="VoidOfSale" finished-at="2024-07-29T13:44:03 IST" duration-ms="181541" status="FAIL">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index 0 out of bounds for length 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
at java.base/java.util.Objects.checkIndex(Objects.java:361)
at java.base/java.util.ArrayList.get(ArrayList.java:427)
at mtestcases.TC_CreditAndDebit.VoidOfSale(TC_CreditAndDebit.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VoidOfSale -->
        <test-method is-config="true" signature="saveXLFile()[pri:0, instance:mtestcases.TC_CreditAndDebit@6404f418]" started-at="2024-07-29T13:44:03 IST" name="saveXLFile" finished-at="2024-07-29T13:44:06 IST" duration-ms="3291" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- saveXLFile -->
        <test-method signature="VoidOfSale()[pri:0, instance:mtestcases.TC_CreditAndDebit@6404f418]" started-at="2024-07-29T13:44:06 IST" name="VoidOfSale" finished-at="2024-07-29T13:47:08 IST" duration-ms="181511" status="FAIL">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index 0 out of bounds for length 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
at java.base/java.util.Objects.checkIndex(Objects.java:361)
at java.base/java.util.ArrayList.get(ArrayList.java:427)
at mtestcases.TC_CreditAndDebit.VoidOfSale(TC_CreditAndDebit.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VoidOfSale -->
        <test-method is-config="true" signature="saveXLFile()[pri:0, instance:mtestcases.TC_CreditAndDebit@6404f418]" started-at="2024-07-29T13:47:08 IST" name="saveXLFile" finished-at="2024-07-29T13:47:11 IST" duration-ms="3174" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- saveXLFile -->
        <test-method signature="VoidOfSale()[pri:0, instance:mtestcases.TC_CreditAndDebit@6404f418]" started-at="2024-07-29T13:47:11 IST" name="VoidOfSale" finished-at="2024-07-29T13:50:12 IST" duration-ms="181604" status="FAIL">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index 0 out of bounds for length 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
at java.base/java.util.Objects.checkIndex(Objects.java:361)
at java.base/java.util.ArrayList.get(ArrayList.java:427)
at mtestcases.TC_CreditAndDebit.VoidOfSale(TC_CreditAndDebit.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VoidOfSale -->
        <test-method is-config="true" signature="saveXLFile()[pri:0, instance:mtestcases.TC_CreditAndDebit@6404f418]" started-at="2024-07-29T13:50:12 IST" name="saveXLFile" finished-at="2024-07-29T13:50:16 IST" duration-ms="3303" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- saveXLFile -->
      </class> <!-- mtestcases.TC_CreditAndDebit -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
