<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="gkillare-win87" failures="0" tests="11" name="mtestcases.TC_CreditAndDebit" time="1.635" errors="2" timestamp="2024-08-05T12:13:57 IST" skipped="9">
  <testcase classname="mtestcases.TC_CreditAndDebit" name="VoidOfRefundWithoutsale" time="0.004">
    <skipped/>
  </testcase> <!-- VoidOfRefundWithoutsale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CreditAndDebit" name="saveXLFile" time="0.001">
    <error message="Unresolved compilation problem: 
	setSessionId cannot be resolved or is not a field
" type="java.lang.Error">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
setSessionId cannot be resolved or is not a field

at requestbuilder.ByPass.createSampleTransRequestDocument(ByPass.java:50)
at requestbuilder.ByPass.buildXMLRequest(ByPass.java:26)
at requestbuilder.ByPass.Option0(ByPass.java:115)
at mtestcases.TC_CreditAndDebit.saveXLFile(TC_CreditAndDebit.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:676)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:660)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- saveXLFile -->
  <system-out/>
  <testcase classname="mtestcases.TC_CreditAndDebit" name="VoidOfRefundWithoutsale" time="0.000">
    <skipped/>
  </testcase> <!-- VoidOfRefundWithoutsale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CreditAndDebit" name="VoidOfRefundWithoutsale" time="0.000">
    <skipped/>
  </testcase> <!-- VoidOfRefundWithoutsale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CreditAndDebit" name="VoidOfRefundWithoutsale" time="0.000">
    <skipped/>
  </testcase> <!-- VoidOfRefundWithoutsale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CreditAndDebit" name="VoidOfRefundWithoutsale" time="0.000">
    <skipped/>
  </testcase> <!-- VoidOfRefundWithoutsale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CreditAndDebit" name="VoidOfRefundWithoutsale" time="1.630">
    <error message="Unresolved compilation problem: 
	setSessionId cannot be resolved or is not a field
" type="java.lang.Error">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
setSessionId cannot be resolved or is not a field

at requestbuilder.ByPass.createSampleTransRequestDocument(ByPass.java:50)
at requestbuilder.ByPass.buildXMLRequest(ByPass.java:26)
at requestbuilder.ByPass.Random(ByPass.java:175)
at base.POS_APIs.beforeGetCardBinAPIs(POS_APIs.java:25)
at base.BaseClass.performGetCardBin(BaseClass.java:149)
at base.BaseClass.performCreditDebit_RW_Sale(BaseClass.java:284)
at mtestcases.TC_CreditAndDebit.VoidOfRefundWithoutsale(TC_CreditAndDebit.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- VoidOfRefundWithoutsale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CreditAndDebit" name="VoidOfRefundWithoutsale" time="0.000">
    <skipped/>
  </testcase> <!-- VoidOfRefundWithoutsale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CreditAndDebit" name="VoidOfRefundWithoutsale" time="0.000">
    <skipped/>
  </testcase> <!-- VoidOfRefundWithoutsale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CreditAndDebit" name="VoidOfRefundWithoutsale" time="0.000">
    <skipped/>
  </testcase> <!-- VoidOfRefundWithoutsale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CreditAndDebit" name="VoidOfRefundWithoutsale" time="0.000">
    <skipped/>
  </testcase> <!-- VoidOfRefundWithoutsale -->
  <system-out/>
</testsuite> <!-- mtestcases.TC_CreditAndDebit -->
